# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: large_array.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11large_array.proto\x12\nlargearray\"\x07\n\x05\x45mpty\">\n\x12LargeArrayResponse\x12(\n\x07objects\x18\x01 \x03(\x0b\x32\x17.largearray.LargeObject\"T\n\x0bLargeObject\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x02\x12\x0e\n\x06\x61\x63tive\x18\x04 \x01(\x08\x12\x0c\n\x04tags\x18\x05 \x03(\t2W\n\x11LargeArrayService\x12\x42\n\rGetLargeArray\x12\x11.largearray.Empty\x1a\x1e.largearray.LargeArrayResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'large_array_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=33
  _globals['_EMPTY']._serialized_end=40
  _globals['_LARGEARRAYRESPONSE']._serialized_start=42
  _globals['_LARGEARRAYRESPONSE']._serialized_end=104
  _globals['_LARGEOBJECT']._serialized_start=106
  _globals['_LARGEOBJECT']._serialized_end=190
  _globals['_LARGEARRAYSERVICE']._serialized_start=192
  _globals['_LARGEARRAYSERVICE']._serialized_end=279
# @@protoc_insertion_point(module_scope)
