# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import services_pb2 as services__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class CombinedServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetResponse = channel.unary_unary(
                '/services.CombinedService/GetResponse',
                request_serializer=services__pb2.UnaryRequest.SerializeToString,
                response_deserializer=services__pb2.UnaryResponse.FromString,
                _registered_method=True)
        self.SendMessages = channel.stream_unary(
                '/services.CombinedService/SendMessages',
                request_serializer=services__pb2.ClientStreamingRequest.SerializeToString,
                response_deserializer=services__pb2.ClientStreamingResponse.FromString,
                _registered_method=True)
        self.GetMessages = channel.unary_stream(
                '/services.CombinedService/GetMessages',
                request_serializer=services__pb2.ServerStreamingRequest.SerializeToString,
                response_deserializer=services__pb2.ServerStreamingResponse.FromString,
                _registered_method=True)
        self.Chat = channel.stream_stream(
                '/services.CombinedService/Chat',
                request_serializer=services__pb2.BidiStreamingRequest.SerializeToString,
                response_deserializer=services__pb2.BidiStreamingResponse.FromString,
                _registered_method=True)
        self.GetRandomObject = channel.unary_unary(
                '/services.CombinedService/GetRandomObject',
                request_serializer=services__pb2.RandomObjectRequest.SerializeToString,
                response_deserializer=services__pb2.RandomObject.FromString,
                _registered_method=True)


class CombinedServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetResponse(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessages(self, request_iterator, context):
        """Client Streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessages(self, request, context):
        """Server Streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request_iterator, context):
        """Bidirectional Streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRandomObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CombinedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResponse,
                    request_deserializer=services__pb2.UnaryRequest.FromString,
                    response_serializer=services__pb2.UnaryResponse.SerializeToString,
            ),
            'SendMessages': grpc.stream_unary_rpc_method_handler(
                    servicer.SendMessages,
                    request_deserializer=services__pb2.ClientStreamingRequest.FromString,
                    response_serializer=services__pb2.ClientStreamingResponse.SerializeToString,
            ),
            'GetMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=services__pb2.ServerStreamingRequest.FromString,
                    response_serializer=services__pb2.ServerStreamingResponse.SerializeToString,
            ),
            'Chat': grpc.stream_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=services__pb2.BidiStreamingRequest.FromString,
                    response_serializer=services__pb2.BidiStreamingResponse.SerializeToString,
            ),
            'GetRandomObject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRandomObject,
                    request_deserializer=services__pb2.RandomObjectRequest.FromString,
                    response_serializer=services__pb2.RandomObject.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.CombinedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('services.CombinedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CombinedService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.CombinedService/GetResponse',
            services__pb2.UnaryRequest.SerializeToString,
            services__pb2.UnaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessages(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/services.CombinedService/SendMessages',
            services__pb2.ClientStreamingRequest.SerializeToString,
            services__pb2.ClientStreamingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/services.CombinedService/GetMessages',
            services__pb2.ServerStreamingRequest.SerializeToString,
            services__pb2.ServerStreamingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/services.CombinedService/Chat',
            services__pb2.BidiStreamingRequest.SerializeToString,
            services__pb2.BidiStreamingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRandomObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.CombinedService/GetRandomObject',
            services__pb2.RandomObjectRequest.SerializeToString,
            services__pb2.RandomObject.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
