// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: large_array.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_large_array_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_large_array_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_large_array_proto_rawDescGZIP(), []int{0}
}

type LargeArrayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Objects []*LargeObject `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
}

func (x *LargeArrayResponse) Reset() {
	*x = LargeArrayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_large_array_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LargeArrayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LargeArrayResponse) ProtoMessage() {}

func (x *LargeArrayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_large_array_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LargeArrayResponse.ProtoReflect.Descriptor instead.
func (*LargeArrayResponse) Descriptor() ([]byte, []int) {
	return file_large_array_proto_rawDescGZIP(), []int{1}
}

func (x *LargeArrayResponse) GetObjects() []*LargeObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

type LargeObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value  float32  `protobuf:"fixed32,3,opt,name=value,proto3" json:"value,omitempty"`
	Active bool     `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Tags   []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *LargeObject) Reset() {
	*x = LargeObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_large_array_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LargeObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LargeObject) ProtoMessage() {}

func (x *LargeObject) ProtoReflect() protoreflect.Message {
	mi := &file_large_array_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LargeObject.ProtoReflect.Descriptor instead.
func (*LargeObject) Descriptor() ([]byte, []int) {
	return file_large_array_proto_rawDescGZIP(), []int{2}
}

func (x *LargeObject) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LargeObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LargeObject) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *LargeObject) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *LargeObject) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_large_array_proto protoreflect.FileDescriptor

var file_large_array_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x61, 0x72, 0x72, 0x61, 0x79, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x47, 0x0a, 0x12, 0x4c, 0x61, 0x72, 0x67,
	0x65, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31,
	0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x61, 0x72, 0x72, 0x61, 0x79, 0x2e, 0x4c, 0x61, 0x72,
	0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x22, 0x73, 0x0a, 0x0b, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x32, 0x57, 0x0a, 0x11, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x11, 0x2e, 0x6c,
	0x61, 0x72, 0x67, 0x65, 0x61, 0x72, 0x72, 0x61, 0x79, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x1e, 0x2e, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x61, 0x72, 0x72, 0x61, 0x79, 0x2e, 0x4c, 0x61, 0x72,
	0x67, 0x65, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_large_array_proto_rawDescOnce sync.Once
	file_large_array_proto_rawDescData = file_large_array_proto_rawDesc
)

func file_large_array_proto_rawDescGZIP() []byte {
	file_large_array_proto_rawDescOnce.Do(func() {
		file_large_array_proto_rawDescData = protoimpl.X.CompressGZIP(file_large_array_proto_rawDescData)
	})
	return file_large_array_proto_rawDescData
}

var file_large_array_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_large_array_proto_goTypes = []interface{}{
	(*Empty)(nil),              // 0: largearray.Empty
	(*LargeArrayResponse)(nil), // 1: largearray.LargeArrayResponse
	(*LargeObject)(nil),        // 2: largearray.LargeObject
}
var file_large_array_proto_depIdxs = []int32{
	2, // 0: largearray.LargeArrayResponse.objects:type_name -> largearray.LargeObject
	0, // 1: largearray.LargeArrayService.GetLargeArray:input_type -> largearray.Empty
	1, // 2: largearray.LargeArrayService.GetLargeArray:output_type -> largearray.LargeArrayResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_large_array_proto_init() }
func file_large_array_proto_init() {
	if File_large_array_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_large_array_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_large_array_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LargeArrayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_large_array_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LargeObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_large_array_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_large_array_proto_goTypes,
		DependencyIndexes: file_large_array_proto_depIdxs,
		MessageInfos:      file_large_array_proto_msgTypes,
	}.Build()
	File_large_array_proto = out.File
	file_large_array_proto_rawDesc = nil
	file_large_array_proto_goTypes = nil
	file_large_array_proto_depIdxs = nil
}
